# Generated by Django 2.0.7 on 2018-07-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.BigIntegerField(db_index=True, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('owner_name', models.CharField(max_length=128)),
                ('image_url', models.CharField(max_length=128)),
                ('image_page', models.CharField(max_length=128)),
                ('owner_page', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TagList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_list', models.CharField(max_length=200)),
                ('load_finished', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('tag_list',),
            },
        ),
        migrations.CreateModel(
            name='TagListImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagesbytags.Image')),
                ('tag_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagesbytags.TagList')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='tag_lists',
            field=models.ManyToManyField(through='imagesbytags.TagListImages', to='imagesbytags.TagList'),
        ),
        migrations.AlterUniqueTogether(
            name='taglistimages',
            unique_together={('tag_list', 'image')},
        ),
    ]
